name: Docker Image CI

on: [push]
# on:
#   push:
#     branches: ["main"]

env:
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  BUILD_TIMESTAMP: $(date +%s)

jobs:
  build:
    runs-on: [self-hosted, linux]
    steps:
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        run: echo ${{ secrets.REGISTRY_TOKEN }} | docker login -u ${{ env.REGISTRY_USERNAME }} --password-stdin

      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          docker build . --tag ${{ github.repository }}:${{ BUILD_TIMESTAMP }}
          docker push ${{ github.repository }}:${{ env.BUILD_TIMESTAMP }}
