name: Docker Image CI

on: [push]
# on:
#   push:
#     branches: ["main"]

env:
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  BUILD_TIMESTAMP: $(date +%s)

jobs:
  build:
    runs-on: [self-hosted, linux]
    environment: cicd
    steps:
      - name: Debug env
        run: echo vars ${{ vars }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ github.repository }}:${{ env.BUILD_TIMESTAMP }}
      # - name: Log into registry ${{ env.REGISTRY }}
      #   if: github.event_name != 'pull_request'
      #   run: echo ${{ secrets.REGISTRY_TOKEN }} | docker login -u ${{ env.REGISTRY_USERNAME }} --password-stdin

      # - name: Build the Docker image
      #   run: |
      #     docker build . --tag ${{ github.repository }}:${{ env.BUILD_TIMESTAMP }}
      #     docker push ${{ github.repository }}:${{ env.BUILD_TIMESTAMP }}
