name: Docker Image CI

on: [push]
# on:
#   push:
#     branches: ["main"]

env:
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: [self-hosted, linux]
    environment: cicd
    steps:
      - name: Instance variables
        id: instance
        run: |
          echo "DATE=$(date +%s)" >> $GITHUB_OUTPUT
          echo "REPO=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
        # run: echo "::set-output name=date::$(date +%s)"
      # - name: Lowercase repository
      #   id: lower-repo
      #   run: |
      #     "::set-output name=repository::$(echo "$github.repository" | tr '[:upper:]' '[:lower:]')"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Test outputs
        run: |
          echo "date from previous step '${{ steps.instance.outputs.DATE }}'"
          echo "repo from previous step '${{ steps.instance.outputs.REPO }}'"

      # - name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ steps.lower-repo.outputs.repository }}:${{ steps.date.outputs.date }}
